### PR TITLE
Addfeature with delete feature #82

### PR DESCRIPTION
**Pull request by andrewdlqnguyen**
Check this before pushing the addfeature to master. I made the delete feature off the addfeature branch. Needed some of the code made in this branch. Check this first, merge to sub then master.

One thing that could improve on this is to use change the courseid order when something gets deleted but I dont know how to change that yet.

Prob better to switch it to Ajax but i dont know how to use ajax either hehe...

### CODE REVIEW

**Review by adamstaples — APPROVED** [review]
Looks good to me!

**Review by K-shamG — COMMENTED** [review]
What was needed from addFeature on this branch. Shouldn't add and delete be separate entities?

**Review by RyanWork — CHANGES_REQUESTED** [review]
I only reviewed this on my phone and I didnt get to actually check out the functionality. Can you implement all of the comments that I made and overall tidy up the code a bit? There is a lot of unused comments in the html code that doesnt seem to be needed as part of the main code base.

Tacking onto Kshamina's question. I think these features should be independent as well. Try and keep our feature branches separate as possible. It creates dependencies between our branches and if something in the add branch changes it might break your delete branch. Your branch will also be blocked until the add feature is finished eventhough it probably shouldn't. Can you elaborate on the topic a little?

**Comment by andrewdlqnguyen** [comment]
> What was needed from addFeature on this branch. Shouldn't add and delete be separate entities?

The master didn't have the admin table populated cuz it wasnt merged yet so i used the addfeature that was made since last demo to access the delete button for each of the data.

**Comment by andrewdlqnguyen** [comment]
> What was needed from addFeature on this branch. Shouldn't add and delete be separate entities?

The master didn't have the admin table populated cuz it wasnt merged yet so i used the addfeature that was made since last demo to access the delete button for each of the data.

**Comment by andrewdlqnguyen** [comment]
> I only reviewed this on my phone and I didnt get to actually check out the functionality. Can you implement all of the comments that I made and overall tidy up the code a bit? There is a lot of unused comments in the html code that doesnt seem to be needed as part of the main code base.
> 
> Tacking onto Kshamina's question. I think these features should be independent as well. Try and keep our feature branches separate as possible. It creates dependencies between our branches and if something in the add branch changes it might break your delete branch. Your branch will also be blocked until the add feature is finished eventhough it probably shouldn't. Can you elaborate on the topic a little?

yeee i just needed the table to be populated and that feature was in this branch. Master didn't have it the last time i pulled from it. Didnt want to make another set of implementation to populate the table or it wouldve conflicted this addfeature if it was merged after.

**Pull request merged**
