### PR TITLE
DBConnection Fixes from old Pull Req + Fixed warnings

### PR DESCRIPTION
**Pull request by andrewdlqnguyen**
Hopefully these changes are good compare to the one before. Made a new branch cuz my old locally one wasn't pulling properly.

### CODE REVIEW

**Comment by andrewdlqnguyen** [comment]
sweeettt! okay it built successfully!

**Comment by andrewdlqnguyen** [comment]
This will cover Issue #38 . Once reviewed, Ill merge this and delete the other branch.

I have some data I could populate the DB but will that break the test case?

**Review by K-shamG — APPROVED** [review]
Good for now as a preliminary connection of DB to the view.

**Comment by SupriyaGadigone** [comment]
Looks good for this iteration, I agree

**Review by SupriyaGadigone — APPROVED** [review]

**Pull request merged**
