### PR TITLE
Apply jQuery DataTables for sorting

### LINKED ISSUE #20: Sorting/Ordering
A user should be able to sort the results based on the column (alphabetical, ascending/descending)

### PR DESCRIPTION
**Pull request by K-shamG**
Used jQuery DataTables to enable sorting. It also provided dynamic searching and pagination. 
image

I also removed some unecessary links from <head> I had in results.html. 

Closes #20

### CODE REVIEW

**Review by RyanWork — APPROVED** [review]
Looks okay? Just a question though, how does our table scale when there are a lot of programs for example? I saw this and it might not be an issue for this branch, but maybe later?

image

**Comment by K-shamG** [comment]
> Looks okay? Just a question though, how does our table scale when there are a lot of programs for example? I saw this and it might not be an issue for this branch, but maybe later?
> 
> image

Hmm do you mean courses, not programs? If yes, and the list is super long, jQuery DataTables adds pagination so it will only show 10 or 25 or something (depending on what you select on the UI) per page

**Review by andrewdlqnguyen — APPROVED** [review]
It looks fine to me. 

Only thing is that i dont understand how this "https://cdn.datatables.net/1.10.19/js/jquery..." worked. You took out all the bootstrap and few other links then you made it work through script. LOL teach me!

**Comment by RyanWork** [comment]
> Looks okay? Just a question though, how does our table scale when there are a lot of programs for example? I saw this and it might not be an issue for this branch, but maybe later?
> 
> image

Sorry, I meant like something like the learning outcomes. It lists those 3 now, will it paginate if there are like 30 learning outcomes for example?

**Comment by K-shamG** [comment]
> > Looks okay? Just a question though, how does our table scale when there are a lot of programs for example? I saw this and it might not be an issue for this branch, but maybe later?
> > image
> 
> Sorry, I meant like something like the learning outcomes. It lists those 3 now, will it paginate if there are like 30 learning outcomes for example?

ahhhh that I'm not so sure. I guess we will have to test that one and fix the UI accordingly :O I was thinking it could be a collapse type-o-thing where you can click to expand LO's

**Comment by K-shamG** [comment]
> It looks fine to me.
> 
> Only thing is that i dont understand how this "https://cdn.datatables.net/1.10.19/js/jquery..." worked. You took out all the bootstrap and few other links then you made it work through script. LOL teach me!

Heheh basically I removed all those from results.html but kept them in index. Since results is a thymeleaf fragment called in index, it has all the same head links and scripts applied to it as its all treated as one html file rather than two separate ones

**Pull request merged**
